version: '3'
services:
  gae-python:
    restart: always
    build:
      context: .
      dockerfile: "Dockerfile-dev"
    ports:
      - "8080:8080"
    volumes:
      - ".:/root"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: key.json      
    container_name: 'gae-python'
    working_dir: '/root/'
    tty: true
    command: flask run --host 0.0.0.0 --port 8080